In [2]:
import pygeoj
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
import geojson
from pprint import pprint
from shapely.geometry import Point, Polygon
import geopandas as gpd

In [3]:
#bulk export csv files, only 6 months allowed at
#a time, http://www.wakegov.com/ccbi/publicservices/Pages/default.aspx

crime1=pd.read_csv("1-Jan_May31_2015.csv")
crime2=pd.read_csv("2-Jun_Nov30_2015.csv")
crime3=pd.read_csv("3-Dec2015_May31_2016.csv")
crime4=pd.read_csv("4-20160601_20161130.csv")
crime5=pd.read_csv("5-20161201_20170531.csv")
crime6=pd.read_csv("6-20170601_20171130.csv")

In [4]:
crime7=pd.read_csv("7-20171201_20180531.csv")
crime8=pd.read_csv("8-20180601_20181130.csv")
crime9=pd.read_csv("9-20181201_20190531.csv")
crime10=pd.read_csv("10-20190601_20191130.csv")
crime11=pd.read_csv("11-20191201_20200530.csv")
crime12=pd.read_csv("12_20200601_20201024.csv")

In [5]:
#concatenate all 12 dataframes
crime_database = pd.concat([crime1, crime2, crime3,crime4, crime5, crime6,crime7, crime8, crime9,crime10, crime11, crime12,])
crime_database.head()

,Name,Age At Arrest,Sex,Residence,Employer,Date of Arrest,Arrest Location,ArrestingOfficer,Arresting Agency,Charge
0,"VINSON,BRAXTON MCCRAY",27.0,M,"569 S LITTLE TEXAS KANNAPOLIS, NC 28083",NONE,04-06-2015 13:15:00,"3301 HAMMOND RD. RALEIGH, NC",WR SANDERS-RPD,RALEIGH POLICE DEPARTMENT,FAIL REPRT NEW ADDRESS-SEX OFF (CABARRUS CO)
1,"LORFILS,GILBERT TRAVIS",32.0,M,"ANYWHERE ANYWHERE, NC 27529",NONE,05-31-2015 23:07:00,"2507 NOBLIN RD RALEIGH, NC",RM CARROLL-RPD,RALEIGH POLICE DEPARTMENT,FELONY POSSESSION OF COCAINE
2,"LORFILS,GILBERT TRAVIS",32.0,M,"ANYWHERE ANYWHERE, NC 27529",NONE,05-31-2015 23:07:00,"2507 NOBLIN RD RALEIGH, NC",RM CARROLL-RPD,RALEIGH POLICE DEPARTMENT,RESISTING PUBLIC OFFICER
3,"LORFILS,GILBERT TRAVIS",32.0,M,"ANYWHERE ANYWHERE, NC 27529",NONE,05-31-2015 23:07:00,"2507 NOBLIN RD RALEIGH, NC",RM CARROLL-RPD,RALEIGH POLICE DEPARTMENT,FTA-SPEEDING/DWLR NOT IMP REV
4,"MASSENBURG,MICHAEL",16.0,M,"1501 E JONES ST RALEIGH, NC 27610",NONE,05-31-2015 23:00:00,"1501 E JONES ST RALEIGH, NC 27610",AM HOWARD-RPD,RALEIGH POLICE DEPARTMENT,INJURY TO PERSONAL PROPERTY

In [6]:
crime_database.reset_index(inplace=True)

In [28]:
#Calculating percentage for each gender for crime from 2015-2020
crime_gender = crime_database.groupby("ArrestingOfficer").sum()
crime_gender

                   index  Age At Arrest
ArrestingOfficer
2833KS HUBAL-RPD    2698           60.0
401 GLENWOOD AVE   15185           63.0
579 HAYWOOD ST.    12980           21.0
A  PANCHEV-RDU PD   3786           21.0
A ADAMS-WCS         5090           67.0
...                  ...            ...
ZT WINHEIMER-RPD   38231           62.0
ZV BUMGARDNER-SHP  11480           28.0
ZW WILLIAMS-CPD    15704           17.0
`CA MARTUCCI-RPD   14135           66.0
`LK HICKS-DCC      13508           20.0

[10797 rows x 2 columns]

                                               Charge   index  Age At Arrest
0              (M) PROB VIOL-(F) PROB OUT OF CO(NASH)    8241           22.0
1                         (M) PROB VIOL-(F) PROB VIOL   77438          188.0
2               (M) PROB VIOL-(F) PROB VIOL OUT OF CO    8103           30.0
3                 (M) PROB VIOL-(F) PROB VIOL(CRAVEN)   10390           29.0
4           (M) PROB VIOL-(M) PROB OUT OF CO(HARNETT)   11181           19.0
...                                               ...     ...            ...
33305                   WORTHLESS CHK 4TH SUB OFFENSE  171687          955.0
33306               WORTHLESS CHK CLOSED ACC (DURHAM)   10414           41.0
33307                WORTHLESS CK CLOSED ACCT (VANCE)    7912           56.0
33308          WRONGFUL RETENTION OF A MISPLACED CARD   14360           56.0
33309  WRONGFUL RETENTION OF A MISPLACED CARD(DURHAM)   12467           21.0

[33310 rows x 3 columns]